server:
  port: 7001
eureka:
  instance:
    hostname: localhost #eureka服务端的实例名称
  server:
    enable-self-preservation: false
    eviction-interval-timer-in-ms: 2000
  client:
    #false 表示不向注册中心注册自己
    register-with-eureka: false
    #false 表示自己端就是注册中心，我的职责就是维护实例，并不需要去检索服务
    fetch-registry: false
    service-url:
      defaultZone: "https://${eureka.instance.hostname}:${server.port}/eureka/"